server:
  port: 8080

spring:
  # 数据源配置
  # docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 --name mysql mysql:8.0.28 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=5000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://127.0.0.1:3306/nativemysqlcharactertest?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    url: jdbc:mysql://host.docker.internal:3306/nativemysqlcharactertest?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: 123456
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: false
  threads:
    virtual:
      # 开启虚拟线程
      enabled: true

# 设置日志级别
logging:
  level:
    root: ${LOG_ROOT_LEVEL:info}
    "cc.shacocloud": ${LOG_MASTER_LEVEL:debug}
    "org.hibernate.SQL": debug
    "org.hibernate.orm.jdbc.bind": trace
    "org.hibernate.orm.jdbc.extract": trace

